keys:
    - &admin_scott age15hzqzdp289m868stvw6937hdzt3qqt0hz5uj4tqt7et5yne0s5eq7dhmgn
    - &concourse_ci age1m8g67uukueuknq6zxkdpe3asf7wlxdehzx4rprfjf03dquhy3dvqpj2g6k
         

creation_rules:
    - key_groups:
        - age:
            - *admin_scott
            - *concourse_ci
